# Generated by Django 5.1.3 on 2024-12-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresult',
            name='Total_marks',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
